services:
  postgres:
    image: postgres:15
    container_name: coriolis_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: coriolis_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
